### ISSUE TITLE
BW image

### ISSUE THREAD

**Issue by MaTriXy** [ochornenko/Camera2GLPreview#2]
Hi Oleg How are you ? 
Just saw this sample and running it on Pixel XL2 gets a B/W image 

Any chance i missed something to configure ?

**Comment by ochornenko** [comment]
Captured image format should be YUV420 (using ImageFormat.YUV_420_888 in this sample). Possibly on Pixel XL2 image format is different. You can try to figure out if its capturing YUV420 or different format on your Pixel XL2.

**Comment by MaTriXy** [comment]
Thanks. 
Will do. 
How's life after ooVoo? it's been a long time since i saw you.

**Comment by ochornenko** [comment]
Everything is good), I check it on Pixel XL also when I get a chance.
Thanks,
Oleg

**Comment by ochornenko** [comment]
Fixed
