### ISSUE TITLE
Preview frame is zoomed in

### ISSUE THREAD

**Issue by yassiezar** [ochornenko/Camera2GLPreview#6]
Hi, I'm busy merging your code with that from the [TensorFlow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) Android example to try and use the Camera2 API and JNI to render and process images in real-time. However, the preview looks like its zoomed-in. I thought it might've been the 640x480 resolution you used, but other resolution settings don't work either on my phone (Asus AR ZenPhone). The TensorFlow sample also renders at 640x480 on my phone, but doesn't have this zoomed in issue. 

Do you have an idea where I might start looking for a fix, since I'm not entirely sure what to even Google. The TensorFlow sample has a [configureTransform()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/CameraConnectionFragment.java#L572) method that looks like it applies a matrix transform to the preview. You think that's what's fixing the zoom-in? And if so, how do I port it over to this code where OpenGL is implemented in native code? (I'm not a very strong opengl coder, but I understand the math)

**Comment by ochornenko** [comment]
In VideoRendererYUV420.cpp I call function:
float scaleFactor = aspect_ratio_correction(false, m_backingWidth, m_backingHeight, m_width, m_height);

which corrects aspect ration depends on screen resolution, you can play with it. Aspect ratio of the screen and video frame can be different, so you need to adjust it to fullscreen or pillarbox or letterbox.

**Comment by yassiezar** [comment]
Great, that fixed it. Thanks!

Also, I see you locked the screen to portrait mode. Out of interest, how would you handle screen orientation changes? For me it crashes if I change the orientation (it goes through the `onPause()`/`onResume()` cycle twice for some reason). And overriding `onConfigurationChanged()`also doesn't help since I can't reload my `SurfaceView`  from my main activity. Unless there is another way to reload it?

**Comment by ochornenko** [comment]
Activity orientation change will add more complexity, it depends on android:configChanges if it's not defined in manifest to prevent restarting activity then android will recreate activity after rotation. You will need to handle properly open/close camera if needed. Not sure what you mean by saying "can't reload my SurfaceView from my main activity"
