### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by remarkked** [ochornenko/Camera2GLPreview#9]
Hi, when trying to build gradle give me this error
![err1](https://github.com/ochornenko/Camera2GLPreview/assets/80647291/5f462988-8f4b-415f-9d8b-3eab8072a14c)
and that I get when trying to run cdep.bat
![err2](https://github.com/ochornenko/Camera2GLPreview/assets/80647291/7b8fcea8-a8fd-4a83-9915-156527061f54)
I tried to change path to boot.yml to existing one (https://github.com/jomof/cdep-work/blob/master/boot.yml), but got this
![err3](https://github.com/ochornenko/Camera2GLPreview/assets/80647291/d6325888-70ea-40e2-a7e8-56563d5731ae)
although I know this file has "entry:"
![boot](https://github.com/ochornenko/Camera2GLPreview/assets/80647291/e7f0b6c2-2998-4bc9-a9c0-30f4254937de)
can you help?

**Comment by kernhu** [comment]
I'm running into that issue as well.
 Process 'command 'cdep.bat'' finished with non-zero exit value 1
when i was running cdep.bat, the terminal is stay for a while then auto closed the terminal

**Comment by ochornenko** [comment]
Should be resolved now
